"""added relationship for reviews

Revision ID: d62fda92e255
Revises: 6fc511806de7
Create Date: 2025-04-10 17:10:42.472018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd62fda92e255'
down_revision: Union[str, None] = '6fc511806de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    # ### end Alembic commands ###
